import { useEffect, useState, type Dispatch, type SetStateAction } from 'react';
import { Check, XCircle as CircleSlash, FileText, MessageCircle, Play, RefreshCw, ShieldCheck, Sparkles, Wrench, Pause, Compass as Target, Lightbulb as Brain, Beaker as FlaskConical, Bell, AlertTriangle } from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import { useAuth } from '../../context/AuthContext';
import { Btn, Empty, Loading, Notice, Panel, Severity, useAdminAction, useAdminRpc } from '../components/ui';

type Autonomy = 'observe' | 'suggest' | 'draft' | 'auto_apply' | 'approval_required' | 'disabled';
type Agent = { agent_key: string; label: string; description: string; enabled: boolean; autonomy_level: Autonomy; cadence_minutes: number; max_actions: number; last_run_at?: string; next_run_at?: string };
type Action = { id: string; agent_key?: string; action_type: string; title: string; detail: string; risk: string; autonomy_level: Autonomy; required_permission?: string; target_type?: string; target_id?: string; proposed: Record<string, unknown>; status: string; created_at: string; decision_note?: string; source?: 'legacy' };
type Mission = { id: string; title: string; objective: string; metric_key: string; target_value?: number; deadline?: string; status: string; priority: number; agent_keys: string[]; created_at: string };
type Workflow = { id: string; name: string; description: string; trigger_type: string; enabled: boolean; autonomy_level: Autonomy; run_count: number; last_run_at?: string };
type Tower = {
  settings: { enabled: boolean; kill_switch: boolean; default_autonomy: Autonomy; daily_budget_cents: number; provider: string };
  agents: Agent[]; workflows: Workflow[]; jobs: { id: string; kind: string; status: string; created_at: string }[];
  missions: Mission[]; queue: Action[]; legacy_suggestions: Action[]; incidents: { id: string; severity: string; title: string; detail: string; status: string; created_at: string }[];
  experiments: { id: string; name: string; hypothesis: string; metric_key: string; status: string; winner?: string }[];
  memory: { id: string; memory_key: string; category: string; content: string; confidence: number; enabled: boolean }[];
  notifications: { id: string; title: string; body: string; severity: string; created_at: string }[];
  metrics: { metric_key: string; value: number; recorded_at: string }[];
  costs: { today?: number; total?: number };
};

const tabs = [
  ['overview', 'Overview'], ['agents', 'Agents'], ['missions', 'Missions'], ['queue', 'Action queue'],
  ['workflows', 'Workflows'], ['experiments', 'Experiments'], ['memory', 'AI memory'], ['incidents', 'Incidents'], ['settings', 'Settings'],
] as const;
type Tab = typeof tabs[number][0];

export default function AdminAI() {
  const { can } = useAuth();
  const allowed = can('admin.ai.run');
  const canApprove = can('admin.ai.approve');
  const tower = useAdminRpc<Tower>('admin_ai_control_tower', undefined, allowed);
  const action = useAdminAction();
  const [tab, setTab] = useState<Tab>('overview');
  const [postId, setPostId] = useState('');
  const [commentId, setCommentId] = useState('');
  const [workflow, setWorkflow] = useState('publish');
  const [workflowNote, setWorkflowNote] = useState('');
  const [autonomy, setAutonomy] = useState<Autonomy>('suggest');
  const [killSwitch, setKillSwitch] = useState(false);
  const [enabled, setEnabled] = useState(false);
  const [budget, setBudget] = useState(0);
  const [agentDrafts, setAgentDrafts] = useState<Record<string, { enabled: boolean; autonomy: Autonomy; cadence: number; max: number }>>({});
  const reload = tower.reload;

  useEffect(() => {
    if (!tower.data) return;
    setAutonomy(tower.data.settings.default_autonomy); setKillSwitch(tower.data.settings.kill_switch); setEnabled(tower.data.settings.enabled); setBudget(tower.data.settings.daily_budget_cents);
    setAgentDrafts(Object.fromEntries(tower.data.agents.map(a => [a.agent_key, { enabled: a.enabled, autonomy: a.autonomy_level, cadence: a.cadence_minutes, max: a.max_actions }])));
  }, [tower.data]);

  const run = (key: string, fn: () => Promise<{ error: string | null; text: string }>) => action.run(key, async () => { const result = await fn(); reload(); return result; });
  const rpc = async (name: string, args: Record<string, unknown> = {}) => {
    const { data, error } = await supabase.rpc(name, args);
    return { data, error };
  };
  const scan = () => run('scan', async () => { const { data, error } = await rpc('admin_ai_scan'); return { error: error?.message || null, text: error ? '' : `Scan complete — ${String((data as { suggestions?: number } | null)?.suggestions || 0)} signals checked.` }; });
  const autopilot = () => run('autopilot', async () => { const { data, error } = await rpc('admin_ai_run_autopilot'); return { error: error?.message || null, text: error ? '' : `Autopilot completed ${JSON.stringify(data).slice(0, 140)}` }; });
  const autoFix = () => run('auto-fix', async () => { const { data, error } = await rpc('admin_ai_auto_run'); return { error: error?.message || null, text: error ? '' : `Safe automation applied ${String((data as { applied?: number } | null)?.applied || 0)} repair(s).` }; });
  const decide = (id: string, decision: 'approve' | 'reject' | 'pause' | 'apply') => run(`${decision}-${id}`, async () => { const { error } = await rpc('admin_ai_decide_action', { p_action_id: id, p_decision: decision, p_note: decision }); return { error: error?.message || null, text: error ? '' : `Action ${decision}d.` }; });
  const applyLegacy = (id: string) => run(`legacy-apply-${id}`, async () => { const { error } = await rpc('admin_ai_apply', { p_suggestion_id: id }); return { error: error?.message || null, text: error ? '' : 'Suggestion applied.' }; });
  const dismissLegacy = (id: string) => run(`legacy-dismiss-${id}`, async () => { const { error } = await rpc('admin_ai_dismiss', { p_suggestion_id: id }); return { error: error?.message || null, text: error ? '' : 'Suggestion dismissed.' }; });
  const queueWorkflow = () => run('queue-workflow', async () => { const { error } = await rpc('admin_ai_queue_workflow', { p_post_id: postId.trim(), p_action: workflow, p_note: workflowNote.trim() || null }); return { error: error?.message || null, text: error ? '' : 'Workflow proposal queued for approval.' }; });
  const draftReply = () => run('draft-reply', async () => { const { error } = await rpc('admin_ai_draft_reply', { p_comment_id: commentId.trim() }); return { error: error?.message || null, text: error ? '' : 'Reply draft queued for approval.' }; });
  const saveSettings = () => run('settings', async () => { const { error } = await rpc('admin_ai_set_autopilot', { p_enabled: enabled, p_kill_switch: killSwitch, p_default_autonomy: autonomy, p_budget: budget, p_provider: 'rules' }); return { error: error?.message || null, text: error ? '' : 'Autopilot policy saved.' }; });
  const runAgent = (key: string) => run(`agent-${key}`, async () => { const { data, error } = await rpc('admin_ai_run_agent', { p_agent_key: key }); return { error: error?.message || null, text: error ? '' : `${key} agent queued ${String((data as { queued?: number } | null)?.queued || 0)} action(s).` }; });
  const saveAgent = (agent: Agent) => { const d = agentDrafts[agent.agent_key]; if (!d) return; return run(`save-agent-${agent.agent_key}`, async () => { const { error } = await rpc('admin_ai_set_agent', { p_agent_key: agent.agent_key, p_enabled: d.enabled, p_autonomy: d.autonomy, p_cadence: d.cadence, p_max_actions: d.max }); return { error: error?.message || null, text: error ? '' : `${agent.label} policy saved.` }; }); };

  if (!allowed) return <Notice tone="warn">You need the <code>admin.ai.run</code> permission to open the Admin AI control tower.</Notice>;
  if (tower.loading && !tower.data) return <Loading />;
  if (tower.error) return <Notice tone="error">{tower.error}</Notice>;
  const data = tower.data;
  if (!data) return null;

  return <div>
    <header className="flex flex-wrap items-start justify-between gap-4 mb-5">
      <div><h1 className="font-serif text-2xl text-charcoal flex items-center gap-2"><Sparkles size={21} className="text-bronze" /> Admin AI Autopilot OS</h1><p className="text-sm text-charcoal-muted mt-1 max-w-3xl">Autonomous growth, editorial, commerce, community, reliability and security operations — grounded in live database facts and controlled by owner policy.</p></div>
      <div className="flex flex-wrap gap-2"><Btn variant="ghost" icon={<RefreshCw size={13} />} onClick={reload} busy={tower.loading}>Reload</Btn><Btn icon={<Sparkles size={13} />} onClick={scan} busy={action.busy === 'scan'}>Scan</Btn><Btn icon={<Play size={13} />} onClick={autopilot} busy={action.busy === 'autopilot'} disabled={!canApprove}>Run autopilot</Btn>{canApprove && <Btn variant="ghost" icon={<Wrench size={13} />} onClick={autoFix} busy={action.busy === 'auto-fix'}>Safe repairs</Btn>}</div>
    </header>
    {action.message && <div className="mb-4"><Notice tone={action.message.tone}>{action.message.text}</Notice></div>}
    <div className="flex flex-wrap gap-1 border-b border-taupe/40 mb-5">{tabs.map(([id, label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`px-3 py-2 text-xs ${tab === id ? 'text-bronze border-b-2 border-bronze' : 'text-charcoal-muted'}`}>{label}</button>)}</div>
    {tab === 'overview' && <Overview data={data} onTab={setTab} />}
    {tab === 'agents' && <Agents data={data} drafts={agentDrafts} setDrafts={setAgentDrafts} onRun={runAgent} onSave={saveAgent} busy={action.busy} />}
    {tab === 'missions' && <Missions data={data} run={run} />}
    {tab === 'queue' && <Queue data={data} canApprove={canApprove} decide={decide} applyLegacy={applyLegacy} dismissLegacy={dismissLegacy} busy={action.busy} />}
    {tab === 'workflows' && <Workflows data={data} run={run} busy={action.busy} />}
    {tab === 'experiments' && <Experiments data={data} run={run} />}
    {tab === 'memory' && <Memory data={data} run={run} />}
    {tab === 'incidents' && <Incidents data={data} run={run} />}
    {tab === 'settings' && <Settings data={data} canApprove={canApprove} enabled={enabled} setEnabled={setEnabled} killSwitch={killSwitch} setKillSwitch={setKillSwitch} autonomy={autonomy} setAutonomy={setAutonomy} budget={budget} setBudget={setBudget} save={saveSettings} busy={action.busy} />}
    {tab === 'overview' && <div className="grid lg:grid-cols-2 gap-5 mt-5"><Panel title="Queue a high-impact proposal" icon={<FileText size={15} className="text-bronze" />}><p className="text-xs text-charcoal-muted mb-3">Propose approve, publish, reject or an SEO edit. Applying is always permission and approval checked.</p><div className="space-y-3"><input value={postId} onChange={e => setPostId(e.target.value)} placeholder="Article UUID" className="w-full border border-taupe/50 px-3 py-2 text-sm rounded-sm" /><div className="flex gap-2"><select value={workflow} onChange={e => setWorkflow(e.target.value)} className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"><option value="publish">Publish</option><option value="approve">Approve</option><option value="reject">Reject</option><option value="edit">SEO edit</option></select><input value={workflowNote} onChange={e => setWorkflowNote(e.target.value)} placeholder="Review note" className="flex-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm" /></div><Btn icon={<Play size={13} />} onClick={queueWorkflow} busy={action.busy === 'queue-workflow'} disabled={!postId.trim() || !canApprove}>Queue proposal</Btn></div></Panel><Panel title="Draft a community reply" icon={<MessageCircle size={15} className="text-bronze" />}><p className="text-xs text-charcoal-muted mb-3">Drafts are never posted automatically.</p><div className="flex gap-2"><input value={commentId} onChange={e => setCommentId(e.target.value)} placeholder="Comment UUID" className="flex-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm" /><Btn icon={<MessageCircle size={13} />} onClick={draftReply} busy={action.busy === 'draft-reply'} disabled={!commentId.trim() || !canApprove}>Draft</Btn></div></Panel></div>}
  </div>;
}

function Overview({ data, onTab }: { data: Tower; onTab: (tab: Tab) => void }) {
  const open = data.queue.length; const critical = data.incidents.filter(i => i.severity === 'critical').length; const active = data.missions.filter(m => m.status === 'active').length;
  return <><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-5"><Stat label="Autopilot" value={data.settings.kill_switch ? 'STOPPED' : data.settings.enabled ? 'ON' : 'OFF'} tone={data.settings.kill_switch ? 'text-red-700' : data.settings.enabled ? 'text-green-700' : 'text-charcoal'} /><Stat label="Open actions" value={open} onClick={() => onTab('queue')} /><Stat label="Active missions" value={active} onClick={() => onTab('missions')} /><Stat label="Incidents" value={critical ? `${critical} critical` : data.incidents.length} onClick={() => onTab('incidents')} /><Stat label="AI spend today" value={`${((data.costs.today || 0) / 100).toFixed(2)}`} /></div><Panel title="Autonomy contract" icon={<ShieldCheck size={15} className="text-bronze" />}><div className="grid md:grid-cols-3 gap-3 text-xs text-charcoal-muted"><p><strong className="text-charcoal">Safe:</strong> reliability repair actions may run automatically only when the owner enables Autopilot.</p><p><strong className="text-charcoal">Approval:</strong> publishing, editing, replies, commerce, permissions and experiments stay in the queue.</p><p><strong className="text-charcoal">Stop:</strong> the kill switch pauses all autonomous work immediately; every decision is audited.</p></div></Panel><Panel title="Live signals" icon={<Bell size={15} className="text-bronze" />}><div className="space-y-2">{data.notifications.length ? data.notifications.slice(0, 5).map(n => <div key={n.id} className="flex gap-3 text-sm"><Severity level={n.severity} /><span className="text-charcoal">{n.title}</span><span className="text-xs text-charcoal-muted ml-auto">{new Date(n.created_at).toLocaleDateString()}</span></div>) : <Empty>No unread AI notifications.</Empty>}</div></Panel></>;
}
function Stat({ label, value, onClick, tone = 'text-charcoal' }: { label: string; value: string | number; onClick?: () => void; tone?: string }) { return <button type="button" onClick={onClick} className="text-left bg-white border border-taupe/30 rounded-sm p-4"><p className="text-[10px] uppercase tracking-wide text-charcoal-muted">{label}</p><p className={`text-xl font-serif mt-1 ${tone}`}>{value}</p></button>; }

function Agents({ data, drafts, setDrafts, onRun, onSave, busy }: { data: Tower; drafts: Record<string, { enabled: boolean; autonomy: Autonomy; cadence: number; max: number }>; setDrafts: Dispatch<SetStateAction<Record<string, { enabled: boolean; autonomy: Autonomy; cadence: number; max: number }>>>; onRun: (key: string) => void; onSave: (agent: Agent) => void; busy: string | null }) { return <Panel title="Agent fleet" icon={<Target size={15} className="text-bronze" />}><div className="space-y-3">{data.agents.map(a => { const d = drafts[a.agent_key] || { enabled: a.enabled, autonomy: a.autonomy_level, cadence: a.cadence_minutes, max: a.max_actions }; return <div key={a.agent_key} className="border border-taupe/30 rounded-sm p-4"><div className="flex flex-wrap gap-3 items-start"><div className="flex-1"><div className="flex items-center gap-2"><input type="checkbox" checked={d.enabled} onChange={e => setDrafts(x => ({ ...x, [a.agent_key]: { ...d, enabled: e.target.checked } }))} /><strong className="text-sm text-charcoal">{a.label}</strong><Severity level={d.autonomy === 'auto_apply' ? 'warning' : d.autonomy === 'disabled' ? 'critical' : 'info'} /></div><p className="text-xs text-charcoal-muted mt-1">{a.description}</p></div><select value={d.autonomy} onChange={e => setDrafts(x => ({ ...x, [a.agent_key]: { ...d, autonomy: e.target.value as Autonomy } }))} className="border border-taupe/50 px-2 py-1 text-xs rounded-sm">{autonomyOptions.map(x => <option key={x} value={x}>{x}</option>)}</select><input type="number" min="5" value={d.cadence} onChange={e => setDrafts(x => ({ ...x, [a.agent_key]: { ...d, cadence: Number(e.target.value) } }))} className="w-20 border border-taupe/50 px-2 py-1 text-xs rounded-sm" title="Cadence minutes" /><Btn variant="ghost" onClick={() => onRun(a.agent_key)} busy={busy === `agent-${a.agent_key}`} icon={<Play size={12} />}>Run</Btn><Btn onClick={() => onSave(a)} busy={busy === `save-agent-${a.agent_key}`}>Save</Btn></div></div>; })}</div></Panel>; }
const autonomyOptions: Autonomy[] = ['observe','suggest','draft','auto_apply','approval_required','disabled'];

function Missions({ data, run }: { data: Tower; run: (key: string, fn: () => Promise<{ error: string | null; text: string }>) => void }) { const [title,setTitle]=useState(''); const [objective,setObjective]=useState(''); const [metric,setMetric]=useState('organic_traffic'); const [agents,setAgents]=useState('growth,seo'); const [priority,setPriority]=useState(60); const create=()=>run('mission',async()=>{const {error}=await supabase.rpc('admin_ai_create_mission',{p_title:title,p_objective:objective,p_metric:metric,p_target:null,p_deadline:null,p_agents:agents.split(',').map(x=>x.trim()).filter(Boolean),p_priority:priority});return{error:error?.message||null,text:error?'':'Mission created.'};});return <><Panel title="Create a growth mission" icon={<Target size={15} className="text-bronze" />}><div className="grid md:grid-cols-2 gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Increase organic traffic" className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><input value={metric} onChange={e=>setMetric(e.target.value)} placeholder="Metric key" className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="What should the AI accomplish?" className="md:col-span-2 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><input value={agents} onChange={e=>setAgents(e.target.value)} placeholder="growth,seo" className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><input type="number" value={priority} onChange={e=>setPriority(Number(e.target.value))} placeholder="Priority" className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/></div><Btn className="mt-3" onClick={create} disabled={!title.trim()}>Create mission</Btn></Panel><Panel title="Missions"><div className="space-y-2">{data.missions.length?data.missions.map(m=><div key={m.id} className="flex flex-wrap gap-2 items-center border-b border-taupe/20 py-3"><strong className="text-sm">{m.title}</strong><Severity level={m.status==='active'?'ok':m.status}/><span className="text-xs text-charcoal-muted">{m.objective}</span><span className="ml-auto text-xs">{m.metric_key}</span></div>):<Empty>No missions yet.</Empty>}</div></Panel></>; }

function Queue({ data, canApprove, decide, applyLegacy, dismissLegacy, busy }: { data: Tower; canApprove: boolean; decide: (id: string, decision: 'approve'|'reject'|'pause'|'apply') => void; applyLegacy: (id: string) => void; dismissLegacy: (id: string) => void; busy: string | null }) {
  const actions = [...data.queue, ...data.legacy_suggestions.map(a => ({ ...a, source: 'legacy' as const }))];
  return <Panel title="Approval and automation queue" icon={<FileText size={15} className="text-bronze" />}><div className="space-y-3">{actions.length?actions.map(a=><div key={a.id} className="border border-taupe/30 rounded-sm p-4"><div className="flex flex-wrap gap-2 items-center"><Severity level={a.risk==='critical'?'critical':a.risk==='high'?'warning':a.risk==='low'?'ok':'info'}/><strong className="text-sm">{a.title}</strong><span className="text-[10px] uppercase text-charcoal-muted ml-auto">{a.status} · {a.source ? 'legacy suggestion' : a.autonomy_level}</span></div><p className="text-xs text-charcoal-muted mt-2">{a.detail}</p><p className="text-[11px] text-charcoal-muted mt-2">Agent: {a.agent_key || 'system'} {a.required_permission && `· Requires ${a.required_permission}`}</p>{a.proposed && <pre className="mt-2 bg-gray-50 p-2 rounded text-[10px] overflow-auto max-h-24">{JSON.stringify(a.proposed,null,2)}</pre>}<div className="flex flex-wrap gap-2 mt-3">{canApprove&&a.source?<><Btn onClick={()=>applyLegacy(a.id)} busy={busy===`legacy-apply-${a.id}`} icon={<Check size={12}/>}>Approve &amp; apply</Btn><Btn variant="danger" onClick={()=>dismissLegacy(a.id)} busy={busy===`legacy-dismiss-${a.id}`} icon={<CircleSlash size={12}/>}>Dismiss</Btn></>:canApprove&&<><Btn onClick={()=>decide(a.id,'approve')} busy={busy===`approve-${a.id}`} icon={<Check size={12}/>}>Approve</Btn><Btn onClick={()=>decide(a.id,'apply')} busy={busy===`apply-${a.id}`} icon={<Play size={12}/>}>Apply now</Btn><Btn variant="danger" onClick={()=>decide(a.id,'reject')} busy={busy===`reject-${a.id}`} icon={<CircleSlash size={12}/>}>Reject</Btn><Btn variant="ghost" onClick={()=>decide(a.id,'pause')} busy={busy===`pause-${a.id}`} icon={<Pause size={12}/>}>Pause</Btn></>}</div></div>):<Empty>No pending actions. Run an agent or scan to create proposals.</Empty>}</div></Panel>;
}

function Workflows({ data, run, busy }: { data: Tower; run: (key: string, fn: () => Promise<{ error: string | null; text: string }>) => void; busy: string | null }) { const [name,setName]=useState('Daily growth review'); const [description,setDescription]=useState('Run SEO and growth agents and send proposals to the queue.'); const [agent,setAgent]=useState('growth'); const [autonomy,setAutonomy]=useState<Autonomy>('approval_required'); const create=()=>run('workflow-create',async()=>{const {error}=await supabase.rpc('admin_ai_create_workflow',{p_name:name,p_description:description,p_trigger:'manual',p_autonomy:autonomy,p_steps:[{agent_key:agent,action_type:'inspect',requires_approval:true}]});return{error:error?.message||null,text:error?'':'Workflow created.'};});return <><Panel title="Create workflow" icon={<Play size={15} className="text-bronze" />}><div className="grid md:grid-cols-2 gap-3"><input value={name} onChange={e=>setName(e.target.value)} className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><select value={agent} onChange={e=>setAgent(e.target.value)} className="border border-taupe/50 px-3 py-2 text-sm rounded-sm">{data.agents.map(a=><option key={a.agent_key} value={a.agent_key}>{a.label}</option>)}</select><textarea value={description} onChange={e=>setDescription(e.target.value)} className="md:col-span-2 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><select value={autonomy} onChange={e=>setAutonomy(e.target.value as Autonomy)} className="border border-taupe/50 px-3 py-2 text-sm rounded-sm">{autonomyOptions.map(x=><option key={x} value={x}>{x}</option>)}</select></div><Btn className="mt-3" onClick={create} disabled={!name.trim()}>Create workflow</Btn></Panel><Panel title="Workflow registry"><div className="space-y-2">{data.workflows.length?data.workflows.map(w=><div key={w.id} className="flex flex-wrap items-center gap-3 border-b border-taupe/20 py-3"><strong className="text-sm">{w.name}</strong><span className="text-xs text-charcoal-muted">{w.description}</span><Severity level={w.enabled?'ok':'info'}/><span className="text-xs ml-auto">{w.run_count} runs</span><Btn variant="ghost" onClick={()=>run(`workflow-${w.id}`,async()=>{const {error}=await supabase.rpc('admin_ai_set_workflow',{p_id:w.id,p_enabled:!w.enabled});return{error:error?.message||null,text:error?'':'Workflow toggled.'};})} busy={busy===`workflow-${w.id}`}>{w.enabled?'Disable':'Enable'}</Btn><Btn onClick={()=>run(`workflow-run-${w.id}`,async()=>{const {error}=await supabase.rpc('admin_ai_run_workflow',{p_id:w.id});return{error:error?.message||null,text:error?'':'Workflow run started.'};})} busy={busy===`workflow-run-${w.id}`} disabled={!w.enabled}>Run</Btn></div>):<Empty>No workflows yet.</Empty>}</div></Panel></>; }

function Experiments({ data, run }: { data: Tower; run: (key: string, fn: () => Promise<{ error: string | null; text: string }>) => void }) { const [name,setName]=useState('Headline experiment'); const [metric,setMetric]=useState('click_through_rate'); const create=()=>run('experiment',async()=>{const {error}=await supabase.rpc('admin_ai_create_experiment',{p_name:name,p_hypothesis:'A clearer variant improves the target metric.',p_target_type:'site',p_target_id:null,p_metric:metric,p_variants:[{key:'control',label:'Control'},{key:'variant',label:'AI variant'}]});return{error:error?.message||null,text:error?'':'Experiment created.'};});return <><Panel title="Create controlled experiment" icon={<FlaskConical size={15} className="text-bronze" />}><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="flex-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><input value={metric} onChange={e=>setMetric(e.target.value)} className="border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><Btn onClick={create}>Create</Btn></div></Panel><Panel title="Experiments"><div className="space-y-2">{data.experiments.length?data.experiments.map(e=><div key={e.id} className="flex gap-3 items-center border-b border-taupe/20 py-3"><strong className="text-sm">{e.name}</strong><span className="text-xs text-charcoal-muted">{e.metric_key}</span><Severity level={e.status==='running'?'ok':'info'}/><span className="ml-auto text-xs">{e.winner||'No winner yet'}</span></div>):<Empty>No experiments yet.</Empty>}</div></Panel></>; }

function Memory({ data, run }: { data: Tower; run: (key: string, fn: () => Promise<{ error: string | null; text: string }>) => void }) { const [key,setKey]=useState('brand.voice'); const [content,setContent]=useState('Use a calm, evidence-led editorial tone.'); const save=()=>run('memory',async()=>{const {error}=await supabase.rpc('admin_ai_upsert_memory',{p_key:key,p_category:'brand',p_content:content,p_confidence:1,p_enabled:true});return{error:error?.message||null,text:error?'':'AI memory saved.'};});return <><Panel title="Durable AI memory" icon={<Brain size={15} className="text-bronze" />}><div className="flex gap-2"><input value={key} onChange={e=>setKey(e.target.value)} placeholder="brand.voice" className="w-1/3 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><input value={content} onChange={e=>setContent(e.target.value)} className="flex-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/><Btn onClick={save}>Save memory</Btn></div></Panel><Panel title="Current memory"><div className="space-y-2">{data.memory.length?data.memory.map(m=><div key={m.id} className="border-b border-taupe/20 py-2"><strong className="text-xs">{m.memory_key}</strong><p className="text-sm text-charcoal-muted">{m.content}</p></div>):<Empty>No memory entries yet.</Empty>}</div></Panel></>; }

function Incidents({ data, run }: { data: Tower; run: (key: string, fn: () => Promise<{ error: string | null; text: string }>) => void }) { return <Panel title="Incidents and safety events" icon={<AlertTriangle size={15} className="text-bronze" />}><div className="space-y-3">{data.incidents.length?data.incidents.map(i=><div key={i.id} className="border border-taupe/30 rounded-sm p-4"><div className="flex gap-2 items-center"><Severity level={i.severity}/><strong className="text-sm">{i.title}</strong><span className="ml-auto text-xs">{i.status}</span></div><p className="text-xs text-charcoal-muted mt-2">{i.detail}</p><div className="mt-3"><Btn variant="ghost" onClick={()=>run(`incident-${i.id}`,async()=>{const {error}=await supabase.rpc('admin_ai_resolve_incident',{p_id:i.id,p_status:'resolved',p_resolution:'Reviewed in Admin AI control tower'});return{error:error?.message||null,text:error?'':'Incident resolved.'};})}>Resolve</Btn></div></div>):<Empty>No open incidents.</Empty>}</div></Panel>; }

function Settings({ data, canApprove, enabled, setEnabled, killSwitch, setKillSwitch, autonomy, setAutonomy, budget, setBudget, save, busy }: { data: Tower; canApprove: boolean; enabled: boolean; setEnabled: (v:boolean)=>void; killSwitch:boolean; setKillSwitch:(v:boolean)=>void; autonomy:Autonomy; setAutonomy:(v:Autonomy)=>void; budget:number; setBudget:(v:number)=>void; save:()=>void; busy:string|null }) { return <Panel title="Autonomy policy and guardrails" icon={<ShieldCheck size={15} className="text-bronze" />}><div className="space-y-4"><div className="flex items-center gap-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)} disabled={!canApprove}/><span className="text-sm">Enable autonomous operating mode</span></div><div className="flex items-center gap-3"><input type="checkbox" checked={killSwitch} onChange={e=>setKillSwitch(e.target.checked)} disabled={!canApprove}/><span className="text-sm text-red-700">Emergency kill switch — pause all autonomous actions</span></div><label className="block text-xs text-charcoal-muted">Default autonomy<select value={autonomy} onChange={e=>setAutonomy(e.target.value as Autonomy)} disabled={!canApprove} className="block mt-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm">{autonomyOptions.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="block text-xs text-charcoal-muted">Daily provider budget, cents<input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))} disabled={!canApprove} className="block mt-1 border border-taupe/50 px-3 py-2 text-sm rounded-sm"/></label><p className="text-xs text-charcoal-muted">Provider: <strong>{data.settings.provider}</strong>. The current free-tier engine uses deterministic database rules. A future model must run behind an edge function and may only create proposals.</p>{canApprove&&<Btn onClick={save} busy={busy==='settings'}>Save guardrails</Btn>}</div></Panel>; }
